### ISSUE TITLE
Sweep

### ISSUE THREAD

**Issue by TaylanSoydan** [markschoene/event-ssm#1]
Hi I have read the hydra and wandb documentation but still struggling with doing a parameter sweep. Is there an easy way I'm missing?

**Comment by markschoene** [comment]
Hi @TaylanSoydan, happy to help. Please let me know if the steps below solve your issues.

### Hydra hyperparameter search
Hydra offers the `--multirun` option. Then, you can specify the parameters to search via comma separated lists. For example to search state size 16 and 32 as well as learning rates `1e-5` and `1e-4`, do
```python
python run_training.py --multirun model.ssm.d_ssm=64,128 optimizer.ssm_base_lr=1e-5,1e-4
```

### Wandb sweeps
Very helpful are wandb sweeps if you want to log and summarize your experiments. 
Always make sure to specify `  - ${args_no_hyphens}` in the sweep config to avoid arguments being parsed in `argparse` style, i.e. `--model.ssm.d_ssm=128`.
Hydra expects arguments being specified without hyphens.

Here is an example sweep config:
```yaml
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - logging=wandb
  - task=dvs-gesture
  - model.ssm.dropout=0.2
  - ${args_no_hyphens}
method: random
metric:
  goal: maximize
  name: Performance/Test accuracy
parameters:
  model.ssm.d_ssm:
    values:
      - 64
      - 128
  model.ssm_init.clip_eigs:
    distribution: categorical
    values:
      - true
      - false
  optimizer.ssm_base_lr:
    distribution: log_uniform
    max: -9.9
    min: -12
  optimizer.weight_decay:
    distribution: log_uniform
    max: -2.9
    min: -4.6
program: run_training.py
```
where `config/logging/wandb.yaml` should be something like
```yaml
log_dir: ${output_dir}
interval: 1000
wandb: False
summary_metric: "Performance/Validation accuracy"
project: wandb_project_name
entity: wandb_entity_name
```
